// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class KONGATest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void kongaorder() {
    // Test name: konga_order
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    // Launched the konga url on the browser 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1296x688 | 
    // Maximized the browser
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | click | linkText=Login / Signup | 
    // click on the sign/signup button
    driver.findElement(By.linkText("Login / Signup")).click();
    // 4 | click | id=username | 
    // clicked on the username box
    driver.findElement(By.id("username")).click();
    // 5 | type | id=username | i********n@yahoo.com
    // typed in the my username
    driver.findElement(By.id("username")).sendKeys("i********n@yahoo.com");
    // 6 | click | id=password | 
    // clicked on the password box
    driver.findElement(By.id("password")).click();
    // 7 | type | id=password | ******************
    // Typed in my password
    driver.findElement(By.id("password")).sendKeys("******************");
    // 8 | click | css=.loginForm_loginButton__aq55S | 
    // clicked on the login button
    driver.findElement(By.cssSelector(".loginForm_loginButton__aq55S")).click();
    // 9 | mouseOver | css=.loginForm_loginButton__aq55S | 
    // moved the mouse over the login button while waiting for the page to open
    {
      WebElement element = driver.findElement(By.cssSelector(".loginForm_loginButton__aq55S"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | click | linkText=All Categories | 
    // Clicked on All category menu
    driver.findElement(By.linkText("All Categories")).click();
    // 11 | click | linkText=Macbooks | 
    // click on MacBooks under computers and accessories
    driver.findElement(By.linkText("Macbooks")).click();
    // 12 | click | css=.List_listItem__KlvU2:nth-child(14) .asset_imageCover__ttp_S | 
    // Click on the particular MacBook I wanted to purchase
    driver.findElement(By.cssSelector(".List_listItem__KlvU2:nth-child(14) .asset_imageCover__ttp_S")).click();
    // 13 | click | css=.productDetail_productCtaSticky__71e8u > .button_button__cpnXl | 
    // Clicked on add to cart
    driver.findElement(By.cssSelector(".productDetail_productCtaSticky__71e8u > .button_button__cpnXl")).click();
    // 14 | click | linkText=Continue to Checkout | 
    // Clicked on continue to checkout button
    driver.findElement(By.linkText("Continue to Checkout")).click();
    // 15 | click | css=.deliveryOptions_headerButton__G2Kzc | 
    // Click on change to change the delivery address
    driver.findElement(By.cssSelector(".deliveryOptions_headerButton__G2Kzc")).click();
    // 16 | click | css=.deliveryOptionCard_active__Vhe_4 .button_button__cpnXl | 
    // Click on add delivery address button
    driver.findElement(By.cssSelector(".deliveryOptionCard_active__Vhe_4 .button_button__cpnXl")).click();
    // 17 | mouseOver | css=.deliveryOptionCard_active__Vhe_4 .button_button__cpnXl | 
    // Moved the mouse to the right to select the delivery address I want
    {
      WebElement element = driver.findElement(By.cssSelector(".deliveryOptionCard_active__Vhe_4 .button_button__cpnXl"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 18 | mouseOut | css=.deliveryOptionCard_active__Vhe_4 .button_button__cpnXl | 
    // Moved the mouse over the delivery addresses listed
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 19 | click | name=selectDeliveryAddress | 
    // Clicked on the delivery address I want to use
    driver.findElement(By.name("selectDeliveryAddress")).click();
    // 20 | mouseOver | css=.deliveryCard_deliveryAddressCardContainer__P6sRV:nth-child(4) .deliveryCard_deliveryAddressCard__FCbm0 | 
    // Moved the mouse down to select and click on use the address option
    {
      WebElement element = driver.findElement(By.cssSelector(".deliveryCard_deliveryAddressCardContainer__P6sRV:nth-child(4) .deliveryCard_deliveryAddressCard__FCbm0"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 21 | mouseOut | css=.deliveryCard_deliveryAddressCardContainer__P6sRV:nth-child(4) .deliveryCard_deliveryAddressCard__FCbm0 | 
    // Moved the mouse down to select and click on use the address option
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 22 | click | linkText=Use this Address | 
    // Clicked on use this address button
    driver.findElement(By.linkText("Use this Address")).click();
    // 23 | click | css=.paymentOptions_paymentOptionsContentPayNowHeader__eiuIT input | 
    // Clicked on pay now under payment options
    driver.findElement(By.cssSelector(".paymentOptions_paymentOptionsContentPayNowHeader__eiuIT input")).click();
    // 24 | click | name=placeOrder | 
    // Clicked on place order button
    driver.findElement(By.name("placeOrder")).click();
    // 25 | click | css=.Card > .payment-option-content | 
    // Clicked on Card from the list payment methods displayed
    driver.findElement(By.cssSelector(".Card > .payment-option-content")).click();
    // 26 | click | id=card-number | 
    // Clicked on the card number box
    driver.findElement(By.id("card-number")).click();
    // 27 | type | id=card-number | 5321 **** **** **22 
    // Typed in the card number (Card PAN)
    driver.findElement(By.id("card-number")).sendKeys("5321 **** **** **22 ");
    // 28 | click | id=expiry | 
    // Clicked on the Expiration date box
    driver.findElement(By.id("expiry")).click();
    // 29 | type | id=expiry | **/**
    // typed in the expiration date
    driver.findElement(By.id("expiry")).sendKeys("**/**");
    // 30 | click | id=cvv | 
    // clicked on the card cvv box
    driver.findElement(By.id("cvv")).click();
    // 31 | type | id=cvv | ***
    // typed in the card cvv
    driver.findElement(By.id("cvv")).sendKeys("***");
    // 32 | click | id=card-pin-new | 
    // clicked on the card pin box
    driver.findElement(By.id("card-pin-new")).click();
    // 33 | click | css=#keypads > .keypadbutton:nth-child(4) | 
    // clicked on the first digit of the pin using the keypad
    driver.findElement(By.cssSelector("#keypads > .keypadbutton:nth-child(4)")).click();
    // 34 | click | css=#keypads > .keypadbutton:nth-child(3) | 
    // clicked on the second digit of the pin using the keypad
    driver.findElement(By.cssSelector("#keypads > .keypadbutton:nth-child(3)")).click();
    // 35 | click | css=#keypads > .keypadbutton:nth-child(4) | 
    // clicked on the third digit of the pin using the keypad
    driver.findElement(By.cssSelector("#keypads > .keypadbutton:nth-child(4)")).click();
    // 36 | click | css=#keypads > .keypadbutton:nth-child(3) | 
    // clicked on the fourth digit of the pin using the keypad
    driver.findElement(By.cssSelector("#keypads > .keypadbutton:nth-child(3)")).click();
    // 37 | click | id=validateCardForm | 
    // Clicked on the submit button to send the card data
    driver.findElement(By.id("validateCardForm")).click();
    // 38 | click | css=.data-card | 
    // Clicked and highlight the error message that appears
    driver.findElement(By.cssSelector(".data-card")).click();
    // 39 | verifyText | css=.data-card__title > span | OOPS! AN ERROR OCCURRED
    // Right clicked and verify the message
    assertThat(driver.findElement(By.cssSelector(".data-card__title > span")).getText(), is("OOPS! AN ERROR OCCURRED"));
    // 40 | click | css=.data-card__close | 
    // Closed the iframe 
    driver.findElement(By.cssSelector(".data-card__close")).click();
    // 41 | close |  | 
    // Close the konga window
    driver.close();
  }
}
