// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('KONGA', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('konga_order', async function() {
    // Test name: konga_order
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    // Launched the konga url on the browser 
    await driver.get("https://www.konga.com/")
    // 2 | setWindowSize | 1296x688 | 
    // Maximized the browser
    await driver.manage().window().setRect({ width: 1296, height: 688 })
    // 3 | click | linkText=Login / Signup | 
    // click on the sign/signup button
    await driver.findElement(By.linkText("Login / Signup")).click()
    // 4 | click | id=username | 
    // clicked on the username box
    await driver.findElement(By.id("username")).click()
    // 5 | type | id=username | i********n@yahoo.com
    // typed in the my username
    await driver.findElement(By.id("username")).sendKeys("i********n@yahoo.com")
    // 6 | click | id=password | 
    // clicked on the password box
    await driver.findElement(By.id("password")).click()
    // 7 | type | id=password | ******************
    // Typed in my password
    await driver.findElement(By.id("password")).sendKeys("******************")
    // 8 | click | css=.loginForm_loginButton__aq55S | 
    // clicked on the login button
    await driver.findElement(By.css(".loginForm_loginButton__aq55S")).click()
    // 9 | mouseOver | css=.loginForm_loginButton__aq55S | 
    // moved the mouse over the login button while waiting for the page to open
    {
      const element = await driver.findElement(By.css(".loginForm_loginButton__aq55S"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 10 | click | linkText=All Categories | 
    // Clicked on All category menu
    await driver.findElement(By.linkText("All Categories")).click()
    // 11 | click | linkText=Macbooks | 
    // click on MacBooks under computers and accessories
    await driver.findElement(By.linkText("Macbooks")).click()
    // 12 | click | css=.List_listItem__KlvU2:nth-child(14) .asset_imageCover__ttp_S | 
    // Click on the particular MacBook I wanted to purchase
    await driver.findElement(By.css(".List_listItem__KlvU2:nth-child(14) .asset_imageCover__ttp_S")).click()
    // 13 | click | css=.productDetail_productCtaSticky__71e8u > .button_button__cpnXl | 
    // Clicked on add to cart
    await driver.findElement(By.css(".productDetail_productCtaSticky__71e8u > .button_button__cpnXl")).click()
    // 14 | click | linkText=Continue to Checkout | 
    // Clicked on continue to checkout button
    await driver.findElement(By.linkText("Continue to Checkout")).click()
    // 15 | click | css=.deliveryOptions_headerButton__G2Kzc | 
    // Click on change to change the delivery address
    await driver.findElement(By.css(".deliveryOptions_headerButton__G2Kzc")).click()
    // 16 | click | css=.deliveryOptionCard_active__Vhe_4 .button_button__cpnXl | 
    // Click on add delivery address button
    await driver.findElement(By.css(".deliveryOptionCard_active__Vhe_4 .button_button__cpnXl")).click()
    // 17 | mouseOver | css=.deliveryOptionCard_active__Vhe_4 .button_button__cpnXl | 
    // Moved the mouse to the right to select the delivery address I want
    {
      const element = await driver.findElement(By.css(".deliveryOptionCard_active__Vhe_4 .button_button__cpnXl"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 18 | mouseOut | css=.deliveryOptionCard_active__Vhe_4 .button_button__cpnXl | 
    // Moved the mouse over the delivery addresses listed
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 19 | click | name=selectDeliveryAddress | 
    // Clicked on the delivery address I want to use
    await driver.findElement(By.name("selectDeliveryAddress")).click()
    // 20 | mouseOver | css=.deliveryCard_deliveryAddressCardContainer__P6sRV:nth-child(4) .deliveryCard_deliveryAddressCard__FCbm0 | 
    // Moved the mouse down to select and click on use the address option
    {
      const element = await driver.findElement(By.css(".deliveryCard_deliveryAddressCardContainer__P6sRV:nth-child(4) .deliveryCard_deliveryAddressCard__FCbm0"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 21 | mouseOut | css=.deliveryCard_deliveryAddressCardContainer__P6sRV:nth-child(4) .deliveryCard_deliveryAddressCard__FCbm0 | 
    // Moved the mouse down to select and click on use the address option
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 22 | click | linkText=Use this Address | 
    // Clicked on use this address button
    await driver.findElement(By.linkText("Use this Address")).click()
    // 23 | click | css=.paymentOptions_paymentOptionsContentPayNowHeader__eiuIT input | 
    // Clicked on pay now under payment options
    await driver.findElement(By.css(".paymentOptions_paymentOptionsContentPayNowHeader__eiuIT input")).click()
    // 24 | click | name=placeOrder | 
    // Clicked on place order button
    await driver.findElement(By.name("placeOrder")).click()
    // 25 | click | css=.Card > .payment-option-content | 
    // Clicked on Card from the list payment methods displayed
    await driver.findElement(By.css(".Card > .payment-option-content")).click()
    // 26 | click | id=card-number | 
    // Clicked on the card number box
    await driver.findElement(By.id("card-number")).click()
    // 27 | type | id=card-number | 5321 **** **** **22 
    // Typed in the card number (Card PAN)
    await driver.findElement(By.id("card-number")).sendKeys("5321 **** **** **22 ")
    // 28 | click | id=expiry | 
    // Clicked on the Expiration date box
    await driver.findElement(By.id("expiry")).click()
    // 29 | type | id=expiry | **/**
    // typed in the expiration date
    await driver.findElement(By.id("expiry")).sendKeys("**/**")
    // 30 | click | id=cvv | 
    // clicked on the card cvv box
    await driver.findElement(By.id("cvv")).click()
    // 31 | type | id=cvv | ***
    // typed in the card cvv
    await driver.findElement(By.id("cvv")).sendKeys("***")
    // 32 | click | id=card-pin-new | 
    // clicked on the card pin box
    await driver.findElement(By.id("card-pin-new")).click()
    // 33 | click | css=#keypads > .keypadbutton:nth-child(4) | 
    // clicked on the first digit of the pin using the keypad
    await driver.findElement(By.css("#keypads > .keypadbutton:nth-child(4)")).click()
    // 34 | click | css=#keypads > .keypadbutton:nth-child(3) | 
    // clicked on the second digit of the pin using the keypad
    await driver.findElement(By.css("#keypads > .keypadbutton:nth-child(3)")).click()
    // 35 | click | css=#keypads > .keypadbutton:nth-child(4) | 
    // clicked on the third digit of the pin using the keypad
    await driver.findElement(By.css("#keypads > .keypadbutton:nth-child(4)")).click()
    // 36 | click | css=#keypads > .keypadbutton:nth-child(3) | 
    // clicked on the fourth digit of the pin using the keypad
    await driver.findElement(By.css("#keypads > .keypadbutton:nth-child(3)")).click()
    // 37 | click | id=validateCardForm | 
    // Clicked on the submit button to send the card data
    await driver.findElement(By.id("validateCardForm")).click()
    // 38 | click | css=.data-card | 
    // Clicked and highlight the error message that appears
    await driver.findElement(By.css(".data-card")).click()
    // 39 | verifyText | css=.data-card__title > span | OOPS! AN ERROR OCCURRED
    // Right clicked and verify the message
    assert(await driver.findElement(By.css(".data-card__title > span")).getText() == "OOPS! AN ERROR OCCURRED")
    // 40 | click | css=.data-card__close | 
    // Closed the iframe 
    await driver.findElement(By.css(".data-card__close")).click()
    // 41 | close |  | 
    // Close the konga window
    await driver.close()
  })
})
