# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestKONGA():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_kongaorder(self):
    # Test name: konga_order
    # Step # | name | target | value
    # 1 | open | https://www.konga.com/ | 
    # Launched the konga url on the browser 
    self.driver.get("https://www.konga.com/")
    # 2 | setWindowSize | 1296x688 | 
    # Maximized the browser
    self.driver.set_window_size(1296, 688)
    # 3 | click | linkText=Login / Signup | 
    # click on the sign/signup button
    self.driver.find_element(By.LINK_TEXT, "Login / Signup").click()
    # 4 | click | id=username | 
    # clicked on the username box
    self.driver.find_element(By.ID, "username").click()
    # 5 | type | id=username | i********n@yahoo.com
    # typed in the my username
    self.driver.find_element(By.ID, "username").send_keys("i********n@yahoo.com")
    # 6 | click | id=password | 
    # clicked on the password box
    self.driver.find_element(By.ID, "password").click()
    # 7 | type | id=password | ******************
    # Typed in my password
    self.driver.find_element(By.ID, "password").send_keys("******************")
    # 8 | click | css=.loginForm_loginButton__aq55S | 
    # clicked on the login button
    self.driver.find_element(By.CSS_SELECTOR, ".loginForm_loginButton__aq55S").click()
    # 9 | mouseOver | css=.loginForm_loginButton__aq55S | 
    # moved the mouse over the login button while waiting for the page to open
    element = self.driver.find_element(By.CSS_SELECTOR, ".loginForm_loginButton__aq55S")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 10 | click | linkText=All Categories | 
    # Clicked on All category menu
    self.driver.find_element(By.LINK_TEXT, "All Categories").click()
    # 11 | click | linkText=Macbooks | 
    # click on MacBooks under computers and accessories
    self.driver.find_element(By.LINK_TEXT, "Macbooks").click()
    # 12 | click | css=.List_listItem__KlvU2:nth-child(14) .asset_imageCover__ttp_S | 
    # Click on the particular MacBook I wanted to purchase
    self.driver.find_element(By.CSS_SELECTOR, ".List_listItem__KlvU2:nth-child(14) .asset_imageCover__ttp_S").click()
    # 13 | click | css=.productDetail_productCtaSticky__71e8u > .button_button__cpnXl | 
    # Clicked on add to cart
    self.driver.find_element(By.CSS_SELECTOR, ".productDetail_productCtaSticky__71e8u > .button_button__cpnXl").click()
    # 14 | click | linkText=Continue to Checkout | 
    # Clicked on continue to checkout button
    self.driver.find_element(By.LINK_TEXT, "Continue to Checkout").click()
    # 15 | click | css=.deliveryOptions_headerButton__G2Kzc | 
    # Click on change to change the delivery address
    self.driver.find_element(By.CSS_SELECTOR, ".deliveryOptions_headerButton__G2Kzc").click()
    # 16 | click | css=.deliveryOptionCard_active__Vhe_4 .button_button__cpnXl | 
    # Click on add delivery address button
    self.driver.find_element(By.CSS_SELECTOR, ".deliveryOptionCard_active__Vhe_4 .button_button__cpnXl").click()
    # 17 | mouseOver | css=.deliveryOptionCard_active__Vhe_4 .button_button__cpnXl | 
    # Moved the mouse to the right to select the delivery address I want
    element = self.driver.find_element(By.CSS_SELECTOR, ".deliveryOptionCard_active__Vhe_4 .button_button__cpnXl")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 18 | mouseOut | css=.deliveryOptionCard_active__Vhe_4 .button_button__cpnXl | 
    # Moved the mouse over the delivery addresses listed
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 19 | click | name=selectDeliveryAddress | 
    # Clicked on the delivery address I want to use
    self.driver.find_element(By.NAME, "selectDeliveryAddress").click()
    # 20 | mouseOver | css=.deliveryCard_deliveryAddressCardContainer__P6sRV:nth-child(4) .deliveryCard_deliveryAddressCard__FCbm0 | 
    # Moved the mouse down to select and click on use the address option
    element = self.driver.find_element(By.CSS_SELECTOR, ".deliveryCard_deliveryAddressCardContainer__P6sRV:nth-child(4) .deliveryCard_deliveryAddressCard__FCbm0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 21 | mouseOut | css=.deliveryCard_deliveryAddressCardContainer__P6sRV:nth-child(4) .deliveryCard_deliveryAddressCard__FCbm0 | 
    # Moved the mouse down to select and click on use the address option
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 22 | click | linkText=Use this Address | 
    # Clicked on use this address button
    self.driver.find_element(By.LINK_TEXT, "Use this Address").click()
    # 23 | click | css=.paymentOptions_paymentOptionsContentPayNowHeader__eiuIT input | 
    # Clicked on pay now under payment options
    self.driver.find_element(By.CSS_SELECTOR, ".paymentOptions_paymentOptionsContentPayNowHeader__eiuIT input").click()
    # 24 | click | name=placeOrder | 
    # Clicked on place order button
    self.driver.find_element(By.NAME, "placeOrder").click()
    # 25 | click | css=.Card > .payment-option-content | 
    # Clicked on Card from the list payment methods displayed
    self.driver.find_element(By.CSS_SELECTOR, ".Card > .payment-option-content").click()
    # 26 | click | id=card-number | 
    # Clicked on the card number box
    self.driver.find_element(By.ID, "card-number").click()
    # 27 | type | id=card-number | 5321 **** **** **22 
    # Typed in the card number (Card PAN)
    self.driver.find_element(By.ID, "card-number").send_keys("5321 **** **** **22 ")
    # 28 | click | id=expiry | 
    # Clicked on the Expiration date box
    self.driver.find_element(By.ID, "expiry").click()
    # 29 | type | id=expiry | **/**
    # typed in the expiration date
    self.driver.find_element(By.ID, "expiry").send_keys("**/**")
    # 30 | click | id=cvv | 
    # clicked on the card cvv box
    self.driver.find_element(By.ID, "cvv").click()
    # 31 | type | id=cvv | ***
    # typed in the card cvv
    self.driver.find_element(By.ID, "cvv").send_keys("***")
    # 32 | click | id=card-pin-new | 
    # clicked on the card pin box
    self.driver.find_element(By.ID, "card-pin-new").click()
    # 33 | click | css=#keypads > .keypadbutton:nth-child(4) | 
    # clicked on the first digit of the pin using the keypad
    self.driver.find_element(By.CSS_SELECTOR, "#keypads > .keypadbutton:nth-child(4)").click()
    # 34 | click | css=#keypads > .keypadbutton:nth-child(3) | 
    # clicked on the second digit of the pin using the keypad
    self.driver.find_element(By.CSS_SELECTOR, "#keypads > .keypadbutton:nth-child(3)").click()
    # 35 | click | css=#keypads > .keypadbutton:nth-child(4) | 
    # clicked on the third digit of the pin using the keypad
    self.driver.find_element(By.CSS_SELECTOR, "#keypads > .keypadbutton:nth-child(4)").click()
    # 36 | click | css=#keypads > .keypadbutton:nth-child(3) | 
    # clicked on the fourth digit of the pin using the keypad
    self.driver.find_element(By.CSS_SELECTOR, "#keypads > .keypadbutton:nth-child(3)").click()
    # 37 | click | id=validateCardForm | 
    # Clicked on the submit button to send the card data
    self.driver.find_element(By.ID, "validateCardForm").click()
    # 38 | click | css=.data-card | 
    # Clicked and highlight the error message that appears
    self.driver.find_element(By.CSS_SELECTOR, ".data-card").click()
    # 39 | verifyText | css=.data-card__title > span | OOPS! AN ERROR OCCURRED
    # Right clicked and verify the message
    assert self.driver.find_element(By.CSS_SELECTOR, ".data-card__title > span").text == "OOPS! AN ERROR OCCURRED"
    # 40 | click | css=.data-card__close | 
    # Closed the iframe 
    self.driver.find_element(By.CSS_SELECTOR, ".data-card__close").click()
    # 41 | close |  | 
    # Close the konga window
    self.driver.close()
  
